export class AppConsts{
    neightborhoods = [
        "Afyonkarahisar Osb Mahallesi",
        "Akçin Mahallesi",
        "Akmescit Mahallesi",
        "Ali Çetinkaya Mahallesi",
        "Ali İhsan Paşa Mahallesi",
        "Altındağ Mahallesi",
        "Ataköy Mahallesi",
        "Atatürk Mahallesi",
        "Barbaros Mahallesi",
        "Battalgazi Mahallesi",
        "Bayatcık Mahallesi",
        "Beyazit Mahallesi",
        "Burmalı Mahallesi",
        "Cumhuriyet Mahallesi",
        "Çakır Mahallesi",
        "Dairecep Mahallesi",
        "Demirçevre Mahallesi",
        "Derviş Paşa Mahallesi",
        "Dörtyol Mahallesi",
        "Dumlupınar Mahallesi",
        "Erenler Mahallesi",
        "Ertuğrul Gazi Mahallesi",
        "Esentepe Mahallesi",
        "Eşrefpaşa Mahallesi",
        "Fakıpaşa Mahallesi",
        "Fatih Mahallesi",
        "Fevzi Çakmak Mahallesi",
        "Gazi Mahallesi",
        "Gökhan Mahallesi",
        "Gültepe Mahallesi",
        "Gümüş Tepe Mahallesi",
        "Güvenevler Mahallesi",
        "Halil İbrahim Sultan Mahallesi",
        "Hamidiye Mahallesi",
        "Hasan Karaağaç Mahallesi",
        "Hattat Karahisar Mahallesi",
        "Hisar Mahallesi",
        "Hoca Ahmet Yesevi Mahallesi",
        "Huzur Mahallesi",
        "Hürriyet Mahallesi",
        "İsmail Mahallesi",
        "İstiklal Mahallesi",
        "Kanlıca Mahallesi",
        "Karaman Mahallesi",
        "Karşıyaka Mahallesi",
        "Kasımpaşa Mahallesi",
        "Kayadibi Mahallesi",
        "Kışlacık Mahallesi",
        "Kocatepe Mahallesi",
        "Kocatepe Mahallesi",
        "Kocatepe Mahallesi",
        "Kurtuluş Mahallesi",
        "Kurtuluş Mahallesi",
        "Küçükçobanlı Mahallesi",
        "Mareşal Fevzi Çakmak Mahallesi",
        "Marulcu Mahallesi",
        "Mecidiye Mahallesi",
        "Mehmet Akif Mahallesi",
        "Nazmi Saatçi Mahallesi",
        "Olucak Mahallesi",
        "Orhangazi Mahallesi",
        "Osman Gazi Mahallesi",
        "Osmanlı Mahallesi",
        "Örnek Mahallesi",
        "ÖrnekEvler Mahallesi",
        "SadıkBey Mahallesi",
        "SahipAta Mahallesi",
        "Sakarya Mahallesi",
        "Sandıklı",
        "Selçuklu Mahallesi",
        "Sümer Mahallesi",
        "Şehit Ahmet Mahallesi",
        "Şeker Mahallesi",
        "Taci Ahmet Mahallesi",
        "Taşpinar Mahallesi",
        "Uğur Mahallesi",
        "Ulucami Mahallesi",
        "Uydukent Mahallesi",
        "Veysel Karani Mahallesi",
        "Yaka Mahallesi",
        "Yarenler Mahallesi",
        "Yavuz Selim Mahallesi",
        "Yeni Mahallesi",
        "Yenice Mahallesi",
        "Yeşilyurt Mahallesi",
        "Yunus Emre Mahallesi",
        "Yunuslar Mahallesi",
        "Zafer Mahallesi",
        "Alcalı Köyü",
        "Anıtkaya Köyü",
        "Bayramgazi Köyü",
        "Belkaracaören Köyü",
        "Bostanlı Köyü",
        "Bolvadin",
        "Burhaniye Köyü",
        "Çavdarlı Köyü",
        "Değirmendere Köyü",
        "Gözsüzlü Köyü",
        "Halimoru Köyü",
        "Kaplanlı Köyü",
        "Karaarslan Köyü",
        "Kızıldağ Köyü",
        "Kozluca Köyü",
        "Köprülü Köyü",
        "Küçükkalecik Köyü",
        "Olucak Köyü",
        "Oyuzca Köyü",
        "Saadet Köyü",
        "Saraydüzü Köyü",
        "Sarık Köyü",
        "Sinanpaşa",
        "Yarımca Köyü"
    ];
}